title: Esoterica
#email: your-email@example.com
description:  Mark Pflug's blog.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://markpflug.github.io/"
twitter_username: markpflug
github_username:  markpflug

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
